---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/11 11:32
---
local key = KEYS[1]
local cntKey = key..":cnt"
local val = ARGV[1]
-- 验证码有效时间五分钟，300秒
local ttl = tonumber(redis.call("ttl", key))

if ttl == -1 then
    return -2
elseif ttl == -2 or ttl < 240 then
    redis.call("set", key, val)
    redis.call("expire", key, 300)
    redis.call("set", cntKey, 3)
    redis.call("expire", cntKey, 300)
    return 0
else
    return -1
end